### ISSUE TITLE
Switch from using AES CFB to AES GCM

### ISSUE THREAD

**Issue by aaronjwood** [Unknwon/com#11]
I'd like to propose that this library use AES in GCM mode instead of CFB mode https://github.com/Unknwon/com/blob/28b053d5a2923b87ce8c5a08f3af779894a72758/string.go#L45 https://github.com/Unknwon/com/blob/28b053d5a2923b87ce8c5a08f3af779894a72758/string.go#L61

GCM is fast (can be parallelized) but is also authenticated which is the biggest benefit over CFB and most other modes.

**Comment by Unknwon** [comment]
Thanks, if possible, please propose a PR :smile:
