### ISSUE TITLE
go mod 管理

### ISSUE THREAD

**Issue by liu-song** [unknwon/com#25]
您好，我才用go mod  download 对这个包进行下载的时候 显示为 go.mod unexpect module path"github.com/unknown/com"，请问是release 的时候没有标记具体的版本号的原因吗，使用了
github.com/unknown/com latest 依旧有错误，如果release 的时候指定了版本
github.com/unknown/com V1.0.0  是不是不会出错了

**Comment by unknwon** [comment]
unknwon 不是 unknown...

**Comment by liu-song** [comment]
不好意思，是我写错了，我运行的是这个demo  https://github.com/hequan2017/go-admin
运行go mod download 之后能下载下来
但是go run main.go 之后会有错误
 github.com/Unknwon/com@v0.0.0-20190804042917-757f69c95f3e: parsing go.mod: unexpected module path "github.com/unknwon/com"  是releases 的版本号的原因造成的吗

**Comment by liu-song** [comment]
+ resolved

**Comment by hequan2017** [comment]
问题解决了。

**Comment by hequan2017** [comment]
是引用的地方，没有进行更新造成的。

**Comment by hequan2017** [comment]
打扰了
